AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'examples/**/*'
    - 'lib/asana/resources/*'
    - 'spec/templates/unicorn.rb'
    - 'spec/templates/world.rb'
    - 'test.rb'

RSpec/FilePath:
  Enabled: false

Style/SignalException:
  Enabled: false

LineLength:
  Max: 120
require: rubocop-rspec
