### WARNING: This file is auto-generated by the asana-api-meta repo. Do not
### edit it manually.
require_relative 'resource'

module Asana
  module Resources
    # An _attachment_ object represents any file attached to a task in Asana,
    # whether it's an uploaded file or one associated via a third-party service
    # such as Dropbox or Google Drive.
    class Attachment < Resource

      attr_reader :id

      class << self
        # Returns the plural name of the resource.
        def plural_name
          'attachments'
        end

        # Returns the full record for a single attachment.
        #
        # id - [Id] Globally unique identifier for the attachment.
        def find_by_id(id, client:)

          new(body(client.get("/attachments/#{id}")), client: client)
        end

        # Returns the compact records for all attachments on the task.
        #
        # task - [Id] Globally unique identifier for the task.
        def find_by_task(task:, client:)

          Collection.new(body(client.get("/tasks/#{task}/attachments")), client: client)
        end

        # Returns the compact records for all attachments on the task.
        #
        # data - [Hash] the attributes to post.
        # task - [Id] Globally unique identifier for the task.
        #
        # file - [File] TBD
        def create_on_task(data = {}, task:, file:, client:)
          params = { file: file }.reject { |_,v| v.nil? }
          new(body(client.post("/tasks/#{task}/attachments", body: params)), client: client)
        end
      end

    end
  end
end


