### WARNING: This file is auto-generated by the asana-api-meta repo. Do not
### edit it manually.

module Asana
  module Resources
    # A _unicorn_ is a fantastic animal.
    class Unicorn < Resource


      attr_reader :id

      attr_reader :name

      class << self
        # Returns the plural name of the resource.
        def plural_name
          'unicorns'
        end

        # Creates a new unicorn in a world.
        #
        # Returns the full record of the newly created unicorn.
        #
        # world - [Id] The world to create the unicorn in.
        # data - [Hash] the attributes to post.
        def create(client, world:, **data)
          with_params = data.merge(world: world).reject { |_,v| v.nil? }
          self.new(body(client.post("/unicorns", body: with_params)), client: client)
        end

        # Creates a new unicorn in a world.
        #
        # Returns the full record of the newly created unicorn.
        #
        # world - [Id] The world to create the unicorn in.
        # data - [Hash] the attributes to post.
        def create_in_world(client, world:, **data)

          self.new(body(client.post("/worlds/#{world}/unicorns", body: data)), client: client)
        end

        # Returns the complete unicorn record for a single unicorn.
        #
        # id - [Id] The unicorn to get.
        def find_by_id(client, id)

          self.new(body(client.get("/unicorns/#{id}")), client: client)
        end

        # Returns the compact unicorn records for some filtered set of unicorns.
        # Use one or more of the parameters provided to filter the unicorns returned.
        #
        # world - [Id] The world to filter unicorns on.
        # breed - [Id] The breed to filter unicorns on.
        def find_all(client, world: nil, breed: nil)
          params = { world: world, breed: breed }.reject { |_,v| v.nil? }
          Collection.new(body(client.get("/unicorns", params: params)).map { |data| self.new(data, client: client) }, client: client)
        end

        # Returns the compact unicorn records for all unicorns in the world.
        #
        # world - [Id] The world to find unicorns in.
        def find_by_world(client, world:)

          Collection.new(body(client.get("/worlds/#{world}/unicorns")).map { |data| self.new(data, client: client) }, client: client)
        end
      end

      # Updates the properties of a tag. Only the fields provided in the `data`
      # block will be updated; any unspecified fields will remain unchanged.
      #
      # When using this method, it is best to specify only those fields you wish
      # to change, or else you may overwrite changes made by another user since
      # you last retrieved the task.
      #
      # Returns the complete updated tag record.
      #
      # data - [Hash] the attributes to post.
      def update(**data)

        refresh_with(body(client.put("/unicorns/#{id}", body: data)))
      end

      # Returns a collection of paws belonging to the unicorn.
      def paws()

        Collection.new(body(client.get("/unicorns/#{id}/paws")).map { |data| Resource.new(data, client: client) }, client: client)
      end

      # Returns the newly added paw.
      #
      # paw - [Id] The paw to add.
      # data - [Hash] the attributes to post.
      def add_paw(paw:, **data)
        with_params = data.merge(paw: paw).reject { |_,v| v.nil? }
        Resource.new(body(client.post("/unicorns/#{id}/paws", body: with_params)), client: client)
      end

      # Returns the updated unicorn record.
      #
      # friends - [Array.Id] The friend IDs to add.
      # data - [Hash] the attributes to post.
      def add_friends(friends:, **data)
        with_params = data.merge(friends: friends).reject { |_,v| v.nil? }
        refresh_with(body(client.post("/unicorns/#{id}/friends", body: with_params)))
      end

      # Returns the world of the unicorn.
      def get_world()

        World.new(body(client.get("/unicorns/#{id}/getWorld")), client: client)
      end

      # A specific, existing unicorn can be deleted by making a DELETE request
      # on the URL for that unicorn.
      #
      # Returns an empty data record.
      def delete()

        client.delete("/unicorns/#{id}") && true
      end

    end
  end
end
