### WARNING: This file is auto-generated by the asana-api-meta repo. Do not
### edit it manually.

module Asana
  module Resources
    # A _world_ is a place where unicorns live.
    class World < Resource


      attr_reader :id

      class << self
        # Returns the plural name of the resource.
        def plural_name
          'worlds'
        end

        # Returns the complete world record for a single world.
        #
        # id - [Id] The world to get.
        def find_by_id(client, id)

          self.new(parse(client.get("/worlds/#{id}")).first, client: client)
        end
      end

    end
  end
end
