name: Publish 📦 to RubyGems.org

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-to-rubygems:
    name: Publish 📦 to RubyGems.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}